### ISSUE TITLE
Add Reviews indexer

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento1-vsbridge-indexer#14]
Reviews indexer feature is already implemented as a part of https://github.com/DivanteLtd/magento1-vsbridge-indexer/pull/2

The thing is that we don't want to merge all the changes proposed within this PR into the core as they require some changes. 

The acceptance criteria for this task is to extract the Reviews Indexer, test it and propose this feature as a separate Pull Request

**Comment by afirlejczyk** [comment]
https://github.com/DivanteLtd/magento1-vsbridge-indexer/pull/28
