### ISSUE TITLE
Missing change for new indexnaming  (with storefront-api)

### ISSUE THREAD

**Issue by kkrieger85** [DivanteLtd/magento1-vsbridge-indexer#52]
Setup:

M1  (1.9.4.4) + https://github.com/DivanteLtd/magento1-vsbridge-indexer + https://github.com/DivanteLtd/magento1-vsbridge
ES Index build with shell script: `/shell$ php  vsf_tools.php --action full_reindex --store 1`

Frontend:
https://github.com/DivanteLtd/vue-storefront + https://github.com/DivanteLtd/storefront-api 

Error Message:
```
(node:31063) UnhandledPromiseRejectionWarning: Error: {"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vue_storefront_magento_1_attribute","index_uuid":"_na_","index":"vue_storefront_magento_1_attribute"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vue_storefront_magento_1_attribute","index_uuid":"_na_","index":"vue_storefront_magento_1_attribute"}
(node:31063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47)
```

**Comment by kkrieger85** [comment]
Using vue-storefront-api all works fine

**Comment by afirlejczyk** [comment]
Module can create different index names in ES (depends on configuration) please check what indices have been created using magento1 module.

Magento 1 module does not support ES6+
- it only create ONE index with different types.

There is issue for that: https://github.com/DivanteLtd/magento1-vsbridge-indexer/issues/44
