### ISSUE TITLE
issue while executing "php -f vsf_tools.php -- --action full_reindex --store STORE_ID"

### ISSUE THREAD

**Issue by webdev-ravi** [DivanteLtd/magento1-vsbridge-indexer#53]
Hello All,

There seems to be a bug on module configuration and execution, i had a sneek peak and saw that you had an patch on magento2-vsbridge-indexer, please do also look for the same on this repo, beneath is the issue i am faing using your **develop** branch

PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"}],"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"},"status":400} in /var/www/html/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610
Stack trace:
#0 /var/www/html/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(273): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/magento/lib/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/magento/lib/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/magento/lib/vendor/guzzlehttp/ringph in /var/www/html/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 610

**Comment by afirlejczyk** [comment]
I am not sure of any patch for magento2-vsbridge-indexer.. 
which ES do you use? Exporting for ES5 worked just fine.

**Comment by webdev-ravi** [comment]
I have installed ES7 and using that with this module

**Comment by webdev-ravi** [comment]
> I am not sure of any patch for magento2-vsbridge-indexer..
> which ES do you use? Exporting for ES5 worked just fine.


I have installed ES7 and using that with this module

**Comment by afirlejczyk** [comment]
Module does not support ES6+, only ES5.
There is issue for adding support for ES6+ https://github.com/DivanteLtd/magento1-vsbridge-indexer/issues/44
